import { ArrowLeft, ArrowRight, Check, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { cn } from "@/lib/utils";
import { THEME_COLORS, type ThemeColor } from "@/lib/types";

const THEME_SWATCH: Record<ThemeColor, string> = {
  blue: "bg-blue-600",
  emerald: "bg-emerald-600",
  violet: "bg-violet-600",
  amber: "bg-amber-500",
  rose: "bg-rose-600",
};

export function WelcomeStep({ onBegin }: { onBegin: () => void }) {
  return (
    <>
      <CardHeader>
        <CardTitle>Document everything in your lab</CardTitle>
        <CardDescription>
          This installer creates your administrator. PolySIEM never ships with a default username or password.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <ul className="space-y-2 text-sm text-muted-foreground">
          <li className="flex gap-2"><Check className="size-4 shrink-0 text-primary" /> Inventory for hosts, VMs, containers, services, and storage</li>
          <li className="flex gap-2"><Check className="size-4 shrink-0 text-primary" /> Network and VLAN documentation with routes and exposure</li>
          <li className="flex gap-2"><Check className="size-4 shrink-0 text-primary" /> Read-only integrations for infrastructure and security logs</li>
          <li className="flex gap-2"><Check className="size-4 shrink-0 text-primary" /> AI-assisted investigation and documentation</li>
        </ul>
        <Button className="w-full" onClick={onBegin}>
          Begin installation <ArrowRight className="size-4" />
        </Button>
      </CardContent>
    </>
  );
}

interface AdministratorStepProps {
  username: string;
  displayName: string;
  password: string;
  confirmation: string;
  error: string | null;
  onUsernameChange: (value: string) => void;
  onDisplayNameChange: (value: string) => void;
  onPasswordChange: (value: string) => void;
  onConfirmationChange: (value: string) => void;
  onBack: () => void;
  onContinue: () => void;
}

export function AdministratorStep(props: AdministratorStepProps) {
  return (
    <>
      <CardHeader>
        <CardTitle>Create the administrator</CardTitle>
        <CardDescription>
          Choose the first login credentials. They are not prefilled or generated by PolySIEM.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <form
          className="space-y-4"
          onSubmit={(event) => {
            event.preventDefault();
            props.onContinue();
          }}
        >
          <div className="space-y-2">
            <Label htmlFor="username">Username</Label>
            <Input id="username" autoComplete="username" autoFocus required value={props.username} onChange={(event) => props.onUsernameChange(event.target.value)} />
          </div>
          <div className="space-y-2">
            <Label htmlFor="displayName">Display name <span className="text-muted-foreground">(optional)</span></Label>
            <Input id="displayName" value={props.displayName} onChange={(event) => props.onDisplayNameChange(event.target.value)} />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input id="password" type="password" autoComplete="new-password" required value={props.password} onChange={(event) => props.onPasswordChange(event.target.value)} />
          </div>
          <div className="space-y-2">
            <Label htmlFor="confirm">Confirm password</Label>
            <Input id="confirm" type="password" autoComplete="new-password" required value={props.confirmation} onChange={(event) => props.onConfirmationChange(event.target.value)} />
          </div>
          {props.error && <p role="alert" className="text-sm font-medium text-destructive">{props.error}</p>}
          <div className="flex justify-between">
            <Button type="button" variant="ghost" onClick={props.onBack}>
              <ArrowLeft className="size-4" /> Back
            </Button>
            <Button type="submit">Continue <ArrowRight className="size-4" /></Button>
          </div>
        </form>
      </CardContent>
    </>
  );
}

interface PreferencesStepProps {
  instanceName: string;
  themeColor: ThemeColor;
  error: string | null;
  loading: boolean;
  onInstanceNameChange: (value: string) => void;
  onThemeChange: (value: ThemeColor) => void;
  onBack: () => void;
  onCreate: () => void;
}

export function PreferencesStep(props: PreferencesStepProps) {
  return (
    <>
      <CardHeader>
        <CardTitle>Name your instance and pick a theme</CardTitle>
        <CardDescription>
          Continuing creates the administrator and signs you in so integrations can be configured securely.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="space-y-2">
          <Label htmlFor="instanceName">Instance name</Label>
          <Input id="instanceName" value={props.instanceName} onChange={(event) => props.onInstanceNameChange(event.target.value)} />
        </div>
        <div className="space-y-2">
          <Label>Theme color</Label>
          <div className="flex gap-3">
            {THEME_COLORS.map((color) => (
              <button
                key={color}
                type="button"
                aria-label={`${color} theme`}
                aria-pressed={props.themeColor === color}
                onClick={() => props.onThemeChange(color)}
                className={cn(
                  "flex size-10 items-center justify-center rounded-full transition-transform hover:scale-110",
                  THEME_SWATCH[color],
                  props.themeColor === color && "ring-2 ring-ring ring-offset-2 ring-offset-background",
                )}
              >
                {props.themeColor === color && <Check className="size-5 text-white" />}
              </button>
            ))}
          </div>
          <p className="text-xs capitalize text-muted-foreground">{props.themeColor}</p>
        </div>
        {props.error && <p role="alert" className="text-sm font-medium text-destructive">{props.error}</p>}
        <div className="flex justify-between">
          <Button type="button" variant="ghost" onClick={props.onBack} disabled={props.loading}>
            <ArrowLeft className="size-4" /> Back
          </Button>
          <Button onClick={props.onCreate} disabled={props.loading}>
            {props.loading && <Loader2 className="size-4 animate-spin" />}
            Create administrator
          </Button>
        </div>
      </CardContent>
    </>
  );
}
