import { createHash } from "node:crypto";

/**
 * PolySIEM connector — the reverse-tunnel "last hop" agent.
 *
 * A connector is modelled on a Cloudflare Tunnel connector: it is installed on
 * an internal machine, dials OUT to the PolySIEM edge over WireGuard, and takes
 * its desired configuration from the control plane. Nothing inbound is required
 * at the connector site for the tunnel itself.
 *
 * There are two management transports, and they converge on ONE canonical
 * ruleset and one hash:
 *  - **token poll** (phase 1): the agent pulls `/api/network/connectors/config`
 *    on a timer. Works even when PolySIEM cannot reach the connector at all.
 *  - **SSH push** (phase 2): PolySIEM connects to a restricted `polysiem-connector`
 *    account whose authorized_keys line can only run this agent, and speaks the
 *    STATUS/APPLY stdin protocol — exactly the idiom the Edge NAT agent uses.
 *
 * This module is pure generation (no DB, no network). It produces:
 *  - {@link CONNECTOR_AGENT_SCRIPT}: the POSIX `sh` agent installed on the host.
 *  - {@link canonicalConnectorRuleset} / {@link connectorRulesetHash}: the shared,
 *    deterministic canonicalisation used by BOTH the control plane (to publish
 *    `configHash`, and to hash the SSH APPLY payload) and the on-host agent (to
 *    verify what it parsed before applying).
 *  - {@link connectorRestrictedAuthorizedKey}: the exact authorized_keys line.
 *
 * ONE INTERFACE, MANY EDGES (phase 4): a connector is a standalone thing that can
 * be linked to any number of edge servers. It brings up exactly ONE WireGuard
 * interface carrying one PEER and one ADDRESS per linked edge, and it re-uses its
 * single keypair with all of them. Unlinking an edge removes that peer and that
 * address on the next apply — both sets are reconciled, never merely added to.
 *
 * KEY CUSTODY (do not "simplify"):
 *  - The **SSH** keypair is generated by PolySIEM, one per connector.
 *  - The **WireGuard** keypair is generated by the CONNECTOR, always. PolySIEM
 *    never sends a WireGuard private key to a connector: there is no field for one
 *    anywhere in the APPLY wire protocol. The agent creates
 *    `/etc/polysiem-connector/private.key` (0600) on first use if it is missing and
 *    reports only the derived PUBLIC key through STATUS.
 *
 * NOTE on WireGuard bring-up: the agent creates and configures the interface with
 * `ip link add ... type wireguard` + `wg set` + `ip address replace` + `ip link set up`.
 * The `wg-quick` wrapper is deliberately never invoked — it segfaults on the target
 * Ubuntu 26.04 pre-release LXC image, while kernel netdev creation works fine.
 * Boot persistence is handled by a plain systemd service that runs this agent.
 */

/**
 * Bumped whenever the on-host agent behaviour changes. Reported to the control
 * plane by the poll path and by `STATUS`.
 *
 * `"2"` added the SSH forced-command STATUS/APPLY protocol.
 * `"3"` makes one installed connector serve MANY edges: one interface, one peer
 * and one address per linked edge, destination-scoped last-hop DNAT, and
 * per-peer STATUS lines.
 */
export const CONNECTOR_AGENT_VERSION = "3";

/**
 * Version tag embedded in the canonical ruleset. Bumping it changes every hash,
 * which is exactly what you want when the canonical line format changes.
 *
 * `"2"` is the multi-edge format: the interface name became part of the hashed
 * state, `TUNNEL` lines joined it (one per linked edge), and `ROUTE` lines gained
 * the `localAddress` field that scopes each last-hop DNAT. A v1 hash and a v2
 * hash of "the same" routes therefore differ, deliberately: an agent still on the
 * old format fails closed instead of applying a ruleset it cannot reproduce.
 */
export const CONNECTOR_RULESET_VERSION = "2";

/** Fixed install path of the agent. The systemd unit, sudoers, and forced command all use it. */
export const CONNECTOR_AGENT_PATH = "/usr/local/libexec/polysiem-connector-agent";

/** Unprivileged system account PolySIEM logs into over SSH. Mirrors `polysiem-edge`. */
export const CONNECTOR_SSH_USERNAME = "polysiem-connector";

/** sudoers drop-in installed by the installer, granting NOPASSWD on the agent path only. */
export const CONNECTOR_SUDOERS_PATH = "/etc/sudoers.d/polysiem-connector";

/** Banner line every STATUS response starts with. */
export const CONNECTOR_STATUS_BANNER = "POLYSIEM_CONNECTOR_STATUS_V1";

/** Root-owned, 0700 state directory. */
export const CONNECTOR_CONFIG_DIR = "/etc/polysiem-connector";
/** `KEY=value` installer-written settings (BASE_URL / CONNECTOR_ID / IFACE / POLYSIEM_INSECURE). */
export const CONNECTOR_CONFIG_FILE = `${CONNECTOR_CONFIG_DIR}/config`;
/** 0600 file holding the currently valid `pscx_…` token (install token, then agent token). */
export const CONNECTOR_TOKEN_FILE = `${CONNECTOR_CONFIG_DIR}/token`;
/**
 * Root-owned, 0700 directory holding the WireGuard identity.
 *
 * This is deliberately `/etc/wireguard` and NOT {@link CONNECTOR_CONFIG_DIR}:
 * Proxmox LXC containers run under an AppArmor profile that lets `wg` read
 * `/etc/wireguard/**` but denies other paths, so `wg set … private-key` fails
 * with `fopen: Permission denied` for an otherwise identical 0600 root-owned
 * file kept under /etc/polysiem-connector. Verified on a real Proxmox LXC.
 */
export const CONNECTOR_KEY_DIR = "/etc/wireguard";
/** 0600 WireGuard private key. Generated on the host; never leaves it, never printed. */
export const CONNECTOR_PRIVATE_KEY_FILE = `${CONNECTOR_KEY_DIR}/polysiem-connector.key`;
/** 0644 derived WireGuard public key, kept for operator inspection and STATUS. */
export const CONNECTOR_PUBLIC_KEY_FILE = `${CONNECTOR_KEY_DIR}/polysiem-connector.pub`;
/** Tab-separated enrolment parameters (ENROLLED / CONNECTOR_ID / IFACE / POLL_INTERVAL). */
export const CONNECTOR_TUNNEL_FILE = `${CONNECTOR_CONFIG_DIR}/tunnel`;
/** Tab-separated applied-ruleset state (REVISION / HASH / COUNT / IPTABLES_HASH). */
export const CONNECTOR_STATE_FILE = `${CONNECTOR_CONFIG_DIR}/state`;
/**
 * The last canonical ruleset the agent successfully applied, byte for byte
 * (0600). It is the agent's memory of every linked edge: the boot path replays
 * its `TUNNEL` lines to re-establish all peers and addresses before the first
 * poll, and `STATUS` reads it without having to touch the control plane.
 */
export const CONNECTOR_RULESET_FILE = `${CONNECTOR_CONFIG_DIR}/ruleset`;

/** systemd unit installed by {@link buildConnectorInstallScript}. */
export const CONNECTOR_SERVICE_NAME = "polysiem-connector.service";

/** Stable dispatcher chains. Everything PolySIEM owns hangs off exactly these three. */
export const CONNECTOR_DNAT_CHAIN = "PS_CX_DNAT";
export const CONNECTOR_SNAT_CHAIN = "PS_CX_SNAT";
export const CONNECTOR_FORWARD_CHAIN = "PS_CX_FORWARD";
/** Immutable per-generation chain prefixes (suffixed with the revision number). */
export const CONNECTOR_DNAT_GENERATION_PREFIX = "PS_CX_D_";
export const CONNECTOR_SNAT_GENERATION_PREFIX = "PS_CX_S_";
export const CONNECTOR_FORWARD_GENERATION_PREFIX = "PS_CX_F_";

/**
 * One published last-hop route.
 *
 * `listenPort` is the PUBLIC port, preserved across the tunnel: the edge DNATs
 * `public:listenPort` to `connectorTunnelIp:listenPort`, and the connector DNATs
 * `<iface> -d localAddress dport listenPort` to `targetAddress:targetPort`.
 * `targetAddress:targetPort` is the internal service AS SEEN FROM THE CONNECTOR.
 *
 * `localAddress` is what makes one connector able to serve many edges. It is the
 * connector's OWN tunnel address on the edge that published this route — i.e. the
 * `ConnectorEdgeLink.tunnelAddress` of that link, and the host half of the
 * matching {@link ConnectorTunnel.address}. Two edges may publish the SAME public
 * port to the same connector; without the destination scope those two rules would
 * collide on `-i <iface> --dport <port>` and the second service would be
 * unreachable. Every last-hop DNAT is therefore emitted as
 * `-i <iface> -d <localAddress> -p <proto> --dport <listenPort>`.
 */
export interface ConnectorRoute {
  /** The connector's tunnel address ON THE EDGE THAT PUBLISHED THIS ROUTE. */
  localAddress: string;
  protocol: "tcp" | "udp";
  listenPort: number;
  targetAddress: string;
  targetPort: number;
}

/** WireGuard parameters for the edge side of one tunnel. */
export interface ConnectorEdgeParams {
  /** `host:port` the connector dials out to. */
  endpoint: string;
  /** Edge WireGuard public key (44-char base64). */
  publicKey: string;
  /** CIDRs routed down the tunnel, e.g. `["10.9.9.0/24"]`. A CSV string is accepted too. */
  allowedIps: readonly string[] | string;
  persistentKeepalive: number;
}

/**
 * One edge this connector is linked to — one WireGuard PEER and one ADDRESS on
 * the single interface the connector owns.
 *
 * A connector holds exactly one WireGuard keypair (its identity, generated on the
 * host) and re-uses it with every edge, so a tunnel carries no key material of
 * the connector's own: only the EDGE's public key travels here.
 */
export interface ConnectorTunnel extends ConnectorEdgeParams {
  /**
   * The edge integration's id. Opaque to the agent — it only labels the peer and
   * keeps the canonical ordering stable. `[A-Za-z0-9_-]{1,64}`.
   */
  edgeKey: string;
  /** The connector's tunnel address on THIS edge, in CIDR form (`10.9.9.3/24`). */
  address: string;
}

/**
 * The complete desired state of one connector: the interface it owns, every edge
 * it is linked to, and every last-hop route across all of those edges.
 *
 * This is what {@link canonicalConnectorRuleset} serialises and
 * {@link connectorRulesetHash} hashes, on BOTH sides of the wire.
 */
export interface ConnectorRuleset {
  /** The single WireGuard interface the connector brings up, e.g. `wg0`. */
  interfaceName: string;
  /** One entry per enabled connector↔edge link. */
  tunnels: readonly ConnectorTunnel[];
  /** Every connector-mode route across all linked edges. */
  routes: readonly ConnectorRoute[];
}

/** Body of the 200 response from `POST /api/network/connectors/config`. */
export interface ConnectorConfigPayload extends ConnectorRuleset {
  configHash: string;
  tunnels: ConnectorTunnel[];
  routes: ConnectorRoute[];
  pollIntervalSeconds: number;
}

/**
 * The stdin payload the agent accepts for one SSH `APPLY` — protocol v2.
 *
 * ```text
 * APPLY\n
 * META\t<revision>\t<rulesetHash>\n
 * IFACE\t<interfaceName>\n
 * TUNNEL\t<edgeKey>\t<addressCidr>\t<edgeEndpoint>\t<edgePublicKey>\t<allowedIpsCsv>\t<keepalive>\n  (one per linked edge)
 * ROUTE\t<localAddress>\t<proto>\t<listenPort>\t<targetAddress>\t<targetPort>\n                     (zero or more)
 * END\n
 * ```
 *
 * Everything between the `META` line and `END` is
 * {@link canonicalConnectorRuleset} minus its `CXRULESET` header, so
 * `<rulesetHash>` is exactly `connectorRulesetHash({interfaceName, tunnels, routes})`;
 * the agent rebuilds the canonical form from the lines it parsed and refuses to
 * apply on any mismatch. Success is answered with
 * `APPLIED\t<routeCount>\t<revision>\t<rulesetHash>` on stdout.
 *
 * **There is no private-key field on this wire, by design** — a TUNNEL line
 * carries the EDGE's public key only. The connector owns its own WireGuard
 * identity (see {@link CONNECTOR_PRIVATE_KEY_FILE}) and re-uses that one keypair
 * with every edge it is linked to.
 *
 * The control-plane side renders this payload in `./ssh.ts`
 * (`buildConnectorApplyProtocol`); the parser that must accept it byte for byte
 * lives in {@link CONNECTOR_AGENT_SCRIPT}'s `cmd_apply`, and `agent.test.ts`
 * pins the exact bytes both ends agree on.
 */

/** Mirrors the agent's `valid_if`: at most 15 characters of interface-name alphabet. */
const INTERFACE_NAME_PATTERN = /^[A-Za-z0-9_.:-]{1,15}$/;
/** Mirrors the agent's `valid_edge_key`. Opaque id, never interpolated into a rule. */
const EDGE_KEY_PATTERN = /^[A-Za-z0-9_-]{1,64}$/;
/** Mirrors the agent's `valid_wgkey`: 44 base64 characters ending in `=`. */
const WG_PUBLIC_KEY_PATTERN = /^[A-Za-z0-9+/]{43}=$/;
/** Mirrors the agent's `valid_endpoint`. */
const ENDPOINT_PATTERN = /^[A-Za-z0-9._-]{1,253}:[0-9]{1,5}$/;
/** Mirrors the agent's `valid_allowed` length ceiling. */
const ALLOWED_IPS_MAX_LENGTH = 200;

function isIpv4Address(value: string): boolean {
  const parts = value.split(".");
  if (parts.length !== 4) return false;
  return parts.every((part) => /^(0|[1-9][0-9]{0,2})$/.test(part) && Number(part) <= 255);
}

function isIpv4Cidr(value: string): boolean {
  const parts = value.split("/");
  if (parts.length !== 2) return false;
  if (!/^(0|[1-9][0-9]?)$/.test(parts[1]) || Number(parts[1]) > 32) return false;
  return isIpv4Address(parts[0]);
}

function isValidPort(value: number): boolean {
  return Number.isInteger(value) && value >= 1 && value <= 65535;
}

function isString(value: unknown): value is string {
  return typeof value === "string";
}

/** Throws with a message that names the offending row, never the whole payload. */
function assertField(condition: boolean, message: string): void {
  if (!condition) throw new Error(message);
}

/**
 * Renders one route as its canonical line (without the trailing newline).
 * Throws on anything the on-host agent would refuse, so a malformed row can
 * never be silently folded into a hash the agent will not be able to reproduce.
 */
function canonicalRouteLine(route: ConnectorRoute, index: number): string {
  const where = `connector route #${index + 1}`;
  assertField(
    isString(route.localAddress) && isIpv4Address(route.localAddress),
    `${where}: localAddress must be the connector's IPv4 tunnel address on the edge that published this route`,
  );
  assertField(route.protocol === "tcp" || route.protocol === "udp", `${where}: protocol must be "tcp" or "udp"`);
  assertField(isValidPort(route.listenPort), `${where}: listenPort must be an integer between 1 and 65535`);
  assertField(isValidPort(route.targetPort), `${where}: targetPort must be an integer between 1 and 65535`);
  assertField(
    isString(route.targetAddress) && isIpv4Address(route.targetAddress),
    `${where}: targetAddress must be an IPv4 address`,
  );
  return `ROUTE\t${route.localAddress}\t${route.protocol}\t${route.listenPort}\t${route.targetAddress}\t${route.targetPort}`;
}

/** `["10.9.9.0/24", "10.9.10.0/24"]` (or an equivalent CSV) → `10.9.9.0/24,10.9.10.0/24`. */
function canonicalAllowedIps(value: readonly string[] | string, where: string): string {
  const raw = isString(value) ? value.split(",") : Array.from(value ?? []);
  const items = raw.map((item) => String(item).trim()).filter((item) => item.length > 0);
  assertField(items.length > 0, `${where}: allowedIps must list at least one IPv4 CIDR`);
  for (const item of items) assertField(isIpv4Cidr(item), `${where}: allowedIps entry "${item}" must be an IPv4 CIDR`);
  const csv = items.join(",");
  assertField(csv.length <= ALLOWED_IPS_MAX_LENGTH, `${where}: allowedIps is longer than the agent accepts`);
  return csv;
}

/**
 * Renders one linked edge as its canonical `TUNNEL` line. One line = one
 * WireGuard peer AND one address on the connector's single interface.
 */
function canonicalTunnelLine(tunnel: ConnectorTunnel, index: number): string {
  const where = `connector tunnel #${index + 1}`;
  assertField(isString(tunnel.edgeKey) && EDGE_KEY_PATTERN.test(tunnel.edgeKey), `${where}: edgeKey must match [A-Za-z0-9_-]{1,64}`);
  assertField(
    isString(tunnel.address) && isIpv4Cidr(tunnel.address),
    `${where}: address must be the connector's tunnel address on this edge, in CIDR form`,
  );
  assertField(isString(tunnel.endpoint) && ENDPOINT_PATTERN.test(tunnel.endpoint), `${where}: endpoint must be host:port`);
  assertField(
    isString(tunnel.publicKey) && WG_PUBLIC_KEY_PATTERN.test(tunnel.publicKey),
    `${where}: publicKey must be the edge's 44-character WireGuard public key`,
  );
  assertField(
    Number.isInteger(tunnel.persistentKeepalive) && tunnel.persistentKeepalive >= 0 && tunnel.persistentKeepalive <= 65535,
    `${where}: persistentKeepalive must be an integer between 0 and 65535`,
  );
  const allowedIps = canonicalAllowedIps(tunnel.allowedIps, where);
  return `TUNNEL\t${tunnel.edgeKey}\t${tunnel.address}\t${tunnel.endpoint}\t${tunnel.publicKey}\t${allowedIps}\t${tunnel.persistentKeepalive}`;
}

/** De-duplicates and orders lines exactly the way `LC_ALL=C sort -u` does. */
function sortedUnique(lines: readonly string[]): string[] {
  return Array.from(new Set(lines)).sort();
}

/**
 * Canonical, byte-exact text form of a connector's desired state.
 *
 * FORMAT v2 (frozen — the control plane and the on-host agent must agree byte for byte):
 *
 * ```text
 * CXRULESET\t2\n
 * IFACE\t<interfaceName>\n
 * TUNNEL\t<edgeKey>\t<addressCidr>\t<endpoint>\t<edgePublicKey>\t<allowedIpsCsv>\t<keepalive>\n  (0..n)
 * ROUTE\t<localAddress>\t<protocol>\t<listenPort>\t<targetAddress>\t<targetPort>\n              (0..n)
 * ```
 *
 * Rules:
 *  1. Exactly one `CXRULESET` header and exactly one `IFACE` line, always present
 *     and always in that order, so even a connector with nothing linked to it has
 *     a stable non-empty canonical form (and so the format can be versioned).
 *  2. One `TUNNEL` line per linked edge, then one `ROUTE` line per published
 *     route, fields separated by a single TAB (U+0009).
 *  3. Identical lines are collapsed within each block.
 *  4. Each block is sorted ASCENDING BY BYTE VALUE — plain C-locale ordering, and
 *     the two blocks never interleave (every `TUNNEL` precedes every `ROUTE`).
 *     Every character produced here is ASCII, so JavaScript's default
 *     `Array.prototype.sort()` and `LC_ALL=C sort -u` agree exactly. This is
 *     ordering-independent by construction: the input order never matters.
 *  5. Every line, header included, is terminated by `\n` (so the string always
 *     ends in a newline and never has a trailing blank line).
 *
 * The agent reproduces this with `printf 'CXRULESET\t2\n'` + the `IFACE` line
 * followed by `LC_ALL=C sort -u` over the `TUNNEL` lines and then over the `ROUTE`
 * lines it parsed — out of the JSON on the poll path, off stdin on the SSH path —
 * and refuses to apply anything whose sha256 does not match the hash it was handed.
 */
export function canonicalConnectorRuleset(ruleset: ConnectorRuleset): string {
  const interfaceName = isString(ruleset?.interfaceName) ? ruleset.interfaceName.trim() : "";
  assertField(
    INTERFACE_NAME_PATTERN.test(interfaceName),
    "connector ruleset: interfaceName must be a WireGuard interface name of at most 15 characters",
  );
  const tunnels = sortedUnique((ruleset.tunnels ?? []).map(canonicalTunnelLine));
  const routes = sortedUnique((ruleset.routes ?? []).map(canonicalRouteLine));
  return [`CXRULESET\t${CONNECTOR_RULESET_VERSION}`, `IFACE\t${interfaceName}`, ...tunnels, ...routes].join("\n") + "\n";
}

/**
 * sha256 (lowercase hex) of {@link canonicalConnectorRuleset} encoded as UTF-8.
 * This IS the `configHash` published by `POST /api/network/connectors/config`,
 * and the `<rulesetHash>` carried on the SSH APPLY `META` line.
 */
export function connectorRulesetHash(ruleset: ConnectorRuleset): string {
  return createHash("sha256").update(canonicalConnectorRuleset(ruleset), "utf8").digest("hex");
}

/**
 * The exact `authorized_keys` line PolySIEM installs for a connector.
 *
 * `restrict` disables every channel feature (no pty, no port/agent/X11 forwarding,
 * no user rc), and the forced command means the key cannot run anything except the
 * agent — which itself only understands STATUS and APPLY. This mirrors
 * `restrictedAuthorizedKey` in the Edge NAT integration byte for byte.
 */
export function connectorRestrictedAuthorizedKey(
  publicKey: string,
  agentPath: string = CONNECTOR_AGENT_PATH,
): string {
  const key = String(publicKey ?? "").trim();
  if (
    !/^(ssh-ed25519|ssh-rsa|ecdsa-sha2-nistp(?:256|384|521)|sk-ssh-ed25519@openssh\.com|sk-ecdsa-sha2-nistp256@openssh\.com) [A-Za-z0-9+/]+={0,3}(?: [^\r\n"]*)?$/.test(key)
  ) {
    throw new Error("Invalid connector SSH public key");
  }
  if (!/^\/[A-Za-z0-9._/-]{1,255}$/.test(agentPath)) {
    throw new Error("Invalid connector agent path");
  }
  return `restrict,command="sudo -n ${agentPath}" ${key}`;
}

/**
 * The on-host agent. Installed 0755 at {@link CONNECTOR_AGENT_PATH}, driven by the
 * `polysiem-connector.service` systemd unit as `<agent> run`, and reachable as the
 * `polysiem-connector` account's SSH forced command.
 *
 * Argv subcommands: `run` (poll loop, the default), `once` (a single cycle — the
 * loop re-executes the script for each cycle so `set -e` stays meaningful inside a
 * cycle while a failure never kills the daemon), `status`, `version`.
 *
 * Stdin subcommands (how sshd invokes it — no argv at all): `STATUS` and `APPLY`.
 *
 * Safety ethos mirrors the edge agent: dedicated PolySIEM-owned chains only,
 * immutable generation chains validated with `iptables-restore --test` before
 * anything is committed, a three-chain dispatcher swap, rollback on failure,
 * `flock` around the apply path, atomic 0600 state files, and no jq dependency
 * (JSON is parsed defensively with sed/awk and every field is re-validated).
 */
export const CONNECTOR_AGENT_SCRIPT = `#!/bin/sh
# PolySIEM connector agent (version ${CONNECTOR_AGENT_VERSION}).
#
# Keeps this connector's WireGuard tunnels up and renders the published last-hop
# rules into PolySIEM-owned iptables chains. It takes its desired state either by
# polling the control plane (token transport) or from an SSH push that speaks the
# STATUS/APPLY stdin protocol below. Both paths converge on the same canonical
# ruleset and the same sha256.
#
# ONE connector can serve MANY edge servers. There is exactly one WireGuard
# interface, carrying one peer and one address per linked edge, and one keypair
# re-used with all of them. Peers and addresses are reconciled against the
# desired set on every apply, so unlinking an edge tears its peering down. Each
# route names the tunnel address of the edge that published it, and the last-hop
# DNAT is scoped to that address — two edges may publish the same public port.
#
# The tunnel interface is created and configured with ip(8) + wg(8) directly.
# The distribution's quick-setup wrapper for WireGuard is deliberately never
# invoked: it segfaults on the target container image, while kernel netdev
# creation works fine. Boot persistence comes from the systemd unit that runs
# this script, not from any wrapper-managed interface.
#
# This agent OWNS its WireGuard identity. The private key is generated here, kept
# 0600, and never printed, transmitted, or accepted from the control plane. Only
# the derived public key is ever reported.
set -eu

AGENT_VERSION=${CONNECTOR_AGENT_VERSION}
RULESET_VERSION=${CONNECTOR_RULESET_VERSION}
CONF_DIR=${CONNECTOR_CONFIG_DIR}
CONF_FILE=${CONNECTOR_CONFIG_FILE}
TOKEN_FILE=${CONNECTOR_TOKEN_FILE}
KEY_DIR=${CONNECTOR_KEY_DIR}
KEY_FILE=${CONNECTOR_PRIVATE_KEY_FILE}
PUB_FILE=${CONNECTOR_PUBLIC_KEY_FILE}
TUNNEL_FILE=${CONNECTOR_TUNNEL_FILE}
STATE_FILE=${CONNECTOR_STATE_FILE}
RULESET_FILE=${CONNECTOR_RULESET_FILE}
LOCK_FILE=$CONF_DIR/apply.lock
DNAT=${CONNECTOR_DNAT_CHAIN}
SNAT=${CONNECTOR_SNAT_CHAIN}
FWD=${CONNECTOR_FORWARD_CHAIN}
GEN_D=${CONNECTOR_DNAT_GENERATION_PREFIX}
GEN_S=${CONNECTOR_SNAT_GENERATION_PREFIX}
GEN_F=${CONNECTOR_FORWARD_GENERATION_PREFIX}
MAX_ROUTES=200
MAX_TUNNELS=64
MIN_POLL=5
MAX_POLL=3600
DEFAULT_POLL=30
TAB="$(printf '\\t')"
CR="$(printf '\\r')"
APPLY_DEPS='ip wg iptables iptables-restore awk grep sed tr sort mktemp sha256sum flock install chmod mv rm sysctl'
POLL_DEPS='curl date sleep uname'

log() { printf 'polysiem-connector: %s\\n' "$1" >&2; }

# ---------------------------------------------------------------- validators
valid_if() { [ -n "$1" ] && [ "\${1#????????????????}" = "$1" ] && ! printf %s "$1" | grep -q '[^A-Za-z0-9_.:-]'; }
valid_port() { case "$1" in ''|*[!0-9]*) return 1;; esac; [ "$1" -ge 1 ] && [ "$1" -le 65535 ]; }
valid_uint() { case "$1" in ''|*[!0-9]*) return 1;; esac; [ "$1" -ge 0 ] && [ "$1" -le 999999999 ]; }
valid_revision() { case "$1" in ''|*[!0-9]*) return 1;; esac; [ "$1" -ge 1 ] && [ "$1" -le 999999999 ]; }
# Epoch seconds outgrew valid_uint's range long ago, so they get a digit-count
# check instead of arithmetic that could overflow a 32-bit shell.
valid_epoch() { case "$1" in ''|*[!0-9]*) return 1;; esac; [ "\${#1}" -le 12 ]; }
valid_hash() { [ "\${#1}" -eq 64 ] && ! printf %s "$1" | grep -q '[^0-9a-f]'; }
valid_proto() { case "$1" in tcp|udp) return 0;; *) return 1;; esac; }
valid_ip() { printf '%s\\n' "$1" | awk -F. 'NF==4 { for(i=1;i<=4;i++) if($i !~ /^[0-9]+$/ || $i>255) exit 1; exit 0 } { exit 1 }'; }
valid_cidr() { printf '%s\\n' "$1" | awk -F/ 'NF==2 { split($1,a,"."); if(length(a)!=4) exit 1; for(i=1;i<=4;i++) if(a[i] !~ /^[0-9]+$/ || a[i]>255) exit 1; if($2 !~ /^[0-9]+$/ || $2>32) exit 1; exit 0 } { exit 1 }'; }
valid_wgkey() { [ "\${#1}" -eq 44 ] || return 1; wgk="\${1%=}"; [ "\${#wgk}" -eq 43 ] || return 1; ! printf %s "$wgk" | grep -q '[^A-Za-z0-9+/]'; }
valid_endpoint() { printf %s "$1" | grep -qE '^[A-Za-z0-9._-]+:[0-9]{1,5}$'; }
valid_allowed() { printf %s "$1" | grep -qE '^[0-9./,]{1,200}$'; }
valid_token() { printf %s "$1" | grep -qE '^pscx_[A-Za-z0-9_-]{24,96}$'; }
# The edge integration id that labels a peer. Opaque: it is never interpolated
# into an iptables rule or a wg argument, only into the canonical ruleset.
valid_edge_key() { printf %s "$1" | grep -qE '^[A-Za-z0-9_-]{1,64}$'; }
valid_connector_id() { printf %s "$1" | grep -qE '^[A-Za-z0-9_-]{1,128}$'; }
valid_base_url() { printf %s "$1" | grep -qE '^https?://[A-Za-z0-9._~-]+(:[0-9]{1,5})?(/[A-Za-z0-9._~/-]*)?$'; }

# Every element of a comma-separated allowed-ips list must be a CIDR.
valid_allowed_list() {
  [ -n "$1" ] || return 1
  valid_allowed "$1" || return 1
  al_ok=1; al_old_ifs=$IFS; IFS=,
  for al_item in $1; do valid_cidr "$al_item" || al_ok=0; done
  IFS=$al_old_ifs
  [ "$al_ok" -eq 1 ]
}

# Collapse a value to one printable line so it can never forge a status field.
sanitize() {
  san="$(printf '%s' "\${1:-}" | tr '\\t\\r\\n' '   ')"
  [ -n "$san" ] || san=-
  printf '%s' "$san" | awk '{ print substr($0, 1, 512) }'
}

# ------------------------------------------------------------- tiny key/value
# Tab-separated "KEY<TAB>VALUE" files written atomically at 0600.
kv_value() {
  [ -f "$1" ] || return 0
  awk -F '\\t' -v wanted="$2" '$1 == wanted { print $2; exit }' "$1" 2>/dev/null || true
}

# "KEY=value" installer-written config. Parsed, never sourced.
conf_value() {
  [ -f "$CONF_FILE" ] || return 0
  awk -v k="$1" 'index($0, k "=") == 1 { print substr($0, length(k) + 2); exit }' "$CONF_FILE" 2>/dev/null || true
}

# ------------------------- JSON, parsed with sed/awk (no external JSON tool)
# The payloads come from PolySIEM itself and are small and flat. They are read
# from a file (never passed through argv, so tokens never reach ps output) after
# newlines/tabs are stripped, and every extracted field is re-validated below.
json_str() { sed -n 's/.*"'"$2"'"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p' "$1"; }
json_num() { sed -n 's/.*"'"$2"'"[[:space:]]*:[[:space:]]*\\([0-9][0-9]*\\).*/\\1/p' "$1"; }
frag_str() { printf '%s' "$1" | sed -n 's/.*"'"$2"'"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p'; }
frag_num() { printf '%s' "$1" | sed -n 's/.*"'"$2"'"[[:space:]]*:[[:space:]]*\\([0-9][0-9]*\\).*/\\1/p'; }
# ["10.9.9.0/24","10.9.10.0/24"] -> 10.9.9.0/24,10.9.10.0/24 (the wire's CSV form).
# Every element is re-validated by valid_allowed_list before it is used.
frag_csv() { printf '%s' "$1" | sed -n 's/.*"'"$2"'"[[:space:]]*:[[:space:]]*\\[\\([^]]*\\)\\].*/\\1/p' | tr -d ' "'; }

flatten_json() { tr -d '\\n\\r\\t' < "$1" > "$2"; }

# One line per JSON object, so each route object can be parsed in isolation.
split_objects() { sed 's/{/\\n{/g; s/}/}\\n/g' "$1"; }

require_deps() {
  for binary in $1; do
    command -v "$binary" >/dev/null 2>&1 || { log "missing dependency: $binary"; exit 3; }
  done
}

# The SSH apply path never talks HTTP, so it only needs the rule-plumbing tools.
check_apply_deps() { require_deps "$APPLY_DEPS"; }
check_deps() { require_deps "$APPLY_DEPS"; require_deps "$POLL_DEPS"; }

setup_tmp() {
  install -d -m 0700 "$CONF_DIR"
  if [ -d /run ]; then
    install -d -m 0700 /run/polysiem-connector
    TMPDIR=/run/polysiem-connector
  else
    TMPDIR="$CONF_DIR"
  fi
  export TMPDIR
}

# ------------------------------------------------------------------- config
# Best-effort settings load. An SSH-managed connector may legitimately have no
# config file at all (it needs no token), so nothing here is fatal.
load_config_soft() {
  BASE_URL="$(conf_value BASE_URL)"
  BASE_URL="\${BASE_URL%/}"
  CONNECTOR_ID="$(conf_value CONNECTOR_ID)"
  [ -n "$CONNECTOR_ID" ] || CONNECTOR_ID="$(kv_value "$TUNNEL_FILE" CONNECTOR_ID)"
  IFACE="$(conf_value IFACE)"
  [ -n "$IFACE" ] || IFACE="$(kv_value "$TUNNEL_FILE" IFACE)"
  [ -n "$IFACE" ] || IFACE=wg0
  valid_if "$IFACE" || IFACE=wg0
  INSECURE=0
  CURL_INSECURE=""
}

# Strict load for the polling transport, which cannot work without a base URL.
load_config() {
  [ -f "$CONF_FILE" ] || { log "missing $CONF_FILE"; exit 3; }
  load_config_soft
  valid_base_url "$BASE_URL" || { log 'BASE_URL in the config file is missing or malformed'; exit 3; }
  [ -z "$CONNECTOR_ID" ] || valid_connector_id "$CONNECTOR_ID" || { log 'CONNECTOR_ID is malformed'; exit 3; }
  IFACE="$(conf_value IFACE)"
  [ -n "$IFACE" ] || IFACE="$(kv_value "$TUNNEL_FILE" IFACE)"
  [ -n "$IFACE" ] || IFACE=wg0
  valid_if "$IFACE" || { log 'IFACE is malformed'; exit 3; }

  INSECURE="$(conf_value POLYSIEM_INSECURE)"
  [ -z "\${POLYSIEM_INSECURE:-}" ] || INSECURE="$POLYSIEM_INSECURE"
  [ "$INSECURE" = 1 ] || INSECURE=0
  CURL_INSECURE=""
  [ "$INSECURE" = 0 ] || CURL_INSECURE="-k"
}

load_token() {
  [ -f "$TOKEN_FILE" ] || { log "missing $TOKEN_FILE"; exit 3; }
  TOKEN="$(tr -d ' \\t\\r\\n' < "$TOKEN_FILE")"
  valid_token "$TOKEN" || { log 'the stored connector token is malformed'; exit 3; }
}

# The token lives in the request body file (0600), never in argv, and --fail keeps
# error bodies out of the log. -k is added ONLY when the operator asked for it.
http_post() {
  # shellcheck disable=SC2086
  curl --fail --silent --show-error $CURL_INSECURE \\
    --connect-timeout 10 --max-time 45 \\
    -H 'Content-Type: application/json' \\
    -X POST --data-binary "@$2" -o "$3" "$BASE_URL$1"
}

# ------------------------------------------------ WireGuard identity (ours)
# The private key is created here on first use and never leaves this host: it is
# not sent to the control plane, not accepted from it, and not printed anywhere.
ensure_keypair() {
  # KEY_DIR is /etc/wireguard on purpose: a Proxmox LXC's AppArmor profile lets
  # wg(8) read /etc/wireguard/** and denies other paths, so keeping the key
  # elsewhere makes "wg set ... private-key" fail with fopen: Permission denied.
  install -d -m 0700 "$KEY_DIR"
  if [ ! -s "$KEY_FILE" ]; then
    ( umask 077; wg genkey > "$KEY_FILE.new" )
    [ -s "$KEY_FILE.new" ] || { rm -f "$KEY_FILE.new"; log 'wg genkey produced no key'; exit 3; }
    chmod 0600 "$KEY_FILE.new"
    mv "$KEY_FILE.new" "$KEY_FILE"
    log 'generated a new WireGuard private key'
  fi
  chmod 0600 "$KEY_FILE"
  PUBLIC_KEY="$(wg pubkey < "$KEY_FILE")"
  valid_wgkey "$PUBLIC_KEY" || { log 'could not derive a WireGuard public key from the stored private key'; exit 3; }
  printf '%s\\n' "$PUBLIC_KEY" > "$PUB_FILE.new"
  chmod 0644 "$PUB_FILE.new"
  mv "$PUB_FILE.new" "$PUB_FILE"
}

# Read-only public-key lookup for STATUS: live interface first, then the cached
# public key, then a derivation from the stored private key. Never generates one
# (STATUS must not have side effects) and never emits private material.
connector_public_key() {
  cpk=-
  if command -v wg >/dev/null 2>&1 && ip link show dev "$1" >/dev/null 2>&1; then
    cpk="$(wg show "$1" public-key 2>/dev/null || printf -)"
    valid_wgkey "$cpk" || cpk=-
  fi
  if [ "$cpk" = - ] && [ -s "$PUB_FILE" ]; then
    cpk="$(tr -d ' \\t\\r\\n' < "$PUB_FILE")"
    valid_wgkey "$cpk" || cpk=-
  fi
  if [ "$cpk" = - ] && [ -s "$KEY_FILE" ] && command -v wg >/dev/null 2>&1; then
    cpk="$(wg pubkey < "$KEY_FILE" 2>/dev/null || printf -)"
    valid_wgkey "$cpk" || cpk=-
  fi
  printf '%s' "$cpk"
}

# Enrolment bookkeeping only. Everything about the EDGES this connector is linked
# to lives in the canonical ruleset file, because there is one entry per link now
# and a flat KEY<TAB>VALUE file cannot hold a list.
write_tunnel_file() {
  enrolled="\${1:-1}"
  valid_uint "\${POLL_INTERVAL:-}" || POLL_INTERVAL=$DEFAULT_POLL
  tf="$(mktemp)"; chmod 0600 "$tf"
  printf 'ENROLLED\\t%s\\nCONNECTOR_ID\\t%s\\nIFACE\\t%s\\nPOLL_INTERVAL\\t%s\\n' \\
    "$enrolled" "\${CONNECTOR_ID:-}" "$IFACE" "$POLL_INTERVAL" > "$tf"
  mv "$tf" "$TUNNEL_FILE"
}

load_tunnel_file() {
  POLL_INTERVAL="$(kv_value "$TUNNEL_FILE" POLL_INTERVAL)"
  valid_uint "$POLL_INTERVAL" || POLL_INTERVAL=$DEFAULT_POLL
}

# Column <n> of the first line of kind <k> in the last applied canonical ruleset.
# Used only for read-only reporting; the apply paths read the file line by line.
ruleset_field() {
  [ -s "$RULESET_FILE" ] || return 0
  awk -F '\\t' -v k="$1" -v c="$2" '$1 == k { print $c; exit }' "$RULESET_FILE" 2>/dev/null || true
}

ruleset_tunnel_count() {
  rtc=0
  if [ -s "$RULESET_FILE" ]; then
    rtc="$(awk -F '\\t' '$1 == "TUNNEL" { n++ } END { print n+0 }' "$RULESET_FILE" 2>/dev/null || printf 0)"
  fi
  valid_uint "\${rtc:-}" || rtc=0
  printf '%s' "$rtc"
}

# Top of a /config or /enroll response: the interface this connector owns and how
# often to poll. The per-edge tunnels are parsed separately, one object each.
parse_config_head() {
  flat="$1"
  h_iface="$(json_str "$flat" interfaceName)"
  [ -z "$h_iface" ] || { valid_if "$h_iface" || { log 'control plane sent a malformed interface name'; return 2; }; IFACE="$h_iface"; }
  h_poll="$(json_num "$flat" pollIntervalSeconds)"
  valid_uint "$h_poll" || h_poll=$DEFAULT_POLL
  [ "$h_poll" -ge "$MIN_POLL" ] || h_poll=$MIN_POLL
  [ "$h_poll" -le "$MAX_POLL" ] || h_poll=$MAX_POLL
  POLL_INTERVAL="$h_poll"
  return 0
}

ensure_enrolled() {
  if [ "$(kv_value "$TUNNEL_FILE" ENROLLED)" = 1 ] && [ -s "$KEY_FILE" ]; then
    return 0
  fi
  ensure_keypair
  osinfo="$(uname -srmo 2>/dev/null | tr -c 'A-Za-z0-9._ /+-' ' ' | awk '{ print substr($0, 1, 200) }')"
  hostinfo="$(uname -n 2>/dev/null | tr -c 'A-Za-z0-9.-' ' ' | awk '{ print substr($0, 1, 200) }')"

  body="$(mktemp)"; chmod 0600 "$body"
  resp="$(mktemp)"; chmod 0600 "$resp"
  flat="$(mktemp)"; chmod 0600 "$flat"
  printf '{"token":"%s","publicKey":"%s","agentVersion":"%s","osInfo":"%s","hostname":"%s"}' \\
    "$TOKEN" "$PUBLIC_KEY" "$AGENT_VERSION" "$osinfo" "$hostinfo" > "$body"
  if ! http_post /api/network/connectors/enroll "$body" "$resp"; then
    rm -f "$body" "$resp" "$flat"
    log 'enrollment request failed (check BASE_URL, the install token, and TLS trust)'
    exit 5
  fi
  rm -f "$body"
  flatten_json "$resp" "$flat"
  rm -f "$resp"

  new_id="$(json_str "$flat" connectorId)"
  new_token="$(json_str "$flat" agentToken)"
  if ! valid_connector_id "$new_id"; then rm -f "$flat"; log 'enrollment response had no usable connector id'; exit 5; fi
  if ! valid_token "$new_token"; then rm -f "$flat"; log 'enrollment response had no usable agent token'; exit 5; fi
  CONNECTOR_ID="$new_id"
  # Only the interface name and the poll interval matter here: the tunnels
  # themselves arrive with the very next /config poll, one per linked edge.
  if ! parse_config_head "$flat"; then rm -f "$flat"; exit 5; fi
  rm -f "$flat"

  # The rotated agent token replaces the one-time install token. Written 0600,
  # atomically, and never echoed.
  ( umask 077; printf '%s\\n' "$new_token" > "$TOKEN_FILE.new" )
  chmod 0600 "$TOKEN_FILE.new"
  mv "$TOKEN_FILE.new" "$TOKEN_FILE"
  TOKEN="$new_token"
  write_tunnel_file 1
  log "enrolled as $CONNECTOR_ID"
}

# ------------------------------------------------------------------- tunnel
# Manual, idempotent WireGuard bring-up. No wrapper script is involved.
#
# ONE interface carries ONE PEER and ONE ADDRESS per TUNNEL line of the canonical
# ruleset it is handed, and the single locally-generated keypair is re-used with
# every edge. Both sets are RECONCILED, not merely added to: a peer or an address
# that is no longer in the desired set is removed, so a connector that PolySIEM
# unlinked from an edge loses that peering on the very next apply.
ensure_tunnels() {
  et_file="$1"
  [ -s "$et_file" ] || return 0
  [ -s "$KEY_FILE" ] || return 0
  valid_if "\${IFACE:-}" || return 0
  if ip link show dev "$IFACE" >/dev/null 2>&1; then
    ip -d link show dev "$IFACE" 2>/dev/null | grep -qw wireguard || {
      log "refusing to manage $IFACE: it exists and is not a WireGuard interface"
      exit 3
    }
  else
    ip link add dev "$IFACE" type wireguard
  fi
  wg set "$IFACE" private-key "$KEY_FILE"

  et_peers="$(mktemp)"; chmod 0600 "$et_peers"
  et_addrs="$(mktemp)"; chmod 0600 "$et_addrs"
  awk -F '\\t' '$1 == "TUNNEL" { print $5 }' "$et_file" | LC_ALL=C sort -u > "$et_peers"
  awk -F '\\t' '$1 == "TUNNEL" { print $3 }' "$et_file" | LC_ALL=C sort -u > "$et_addrs"

  while IFS="$TAB" read -r et_kind et_key et_cidr et_end et_pub et_allow et_keep; do
    [ "$et_kind" = TUNNEL ] || continue
    wg set "$IFACE" peer "$et_pub" endpoint "$et_end" allowed-ips "$et_allow" persistent-keepalive "$et_keep"
    ip address replace "$et_cidr" dev "$IFACE"
  done < "$et_file"

  # Reconcile away what is no longer linked. Only this interface is touched, and
  # it is one PolySIEM created (the guard above refuses any other owner).
  for et_have in $(wg show "$IFACE" peers 2>/dev/null || true); do
    grep -qxF "$et_have" "$et_peers" || wg set "$IFACE" peer "$et_have" remove
  done
  for et_have in $(ip -o -4 addr show dev "$IFACE" 2>/dev/null | awk '{ print $4 }'); do
    grep -qxF "$et_have" "$et_addrs" || ip address del "$et_have" dev "$IFACE"
  done
  rm -f "$et_peers" "$et_addrs"

  ip link set "$IFACE" up
}

# Boot / pre-poll path: re-establish every peering from the last ruleset the
# agent successfully applied, so a reboot does not wait for the first poll (and an
# SSH-only connector, which never polls at all, comes back by itself).
resume_tunnels() {
  [ -s "$RULESET_FILE" ] || return 0
  rs_if="$(ruleset_field IFACE 2)"
  valid_if "\${rs_if:-}" || return 0
  IFACE="$rs_if"
  ensure_tunnels "$RULESET_FILE"
}

# up | down | absent. Guarded so an un-provisioned box still answers.
wg_link_state() {
  ip link show dev "$1" >/dev/null 2>&1 || { printf absent; return 0; }
  if ip -o link show dev "$1" 2>/dev/null | sed -n 's/.*<\\([^>]*\\)>.*/\\1/p' | tr ',' '\\n' | grep -qx UP; then
    printf up
  else
    printf down
  fi
}

wg_link_address() {
  wla=-
  if ip link show dev "$1" >/dev/null 2>&1; then
    wla="$(ip -o -4 addr show dev "$1" 2>/dev/null | awk '{ print $4; exit }')"
  fi
  [ -n "\${wla:-}" ] || wla=-
  printf '%s' "$wla"
}

wg_peer_count() {
  wpc=0
  if command -v wg >/dev/null 2>&1 && ip link show dev "$1" >/dev/null 2>&1; then
    wpc="$(wg show "$1" peers 2>/dev/null | awk 'END{print NR+0}')"
  fi
  valid_uint "\${wpc:-}" || wpc=0
  printf '%s' "$wpc"
}

# Newest peer handshake as epoch seconds, or 0 when there has never been one.
wg_latest_handshake() {
  wlh=0
  if command -v wg >/dev/null 2>&1 && ip link show dev "$1" >/dev/null 2>&1; then
    wlh="$(wg show "$1" latest-handshakes 2>/dev/null | awk '{ if ($2+0 > m) m=$2+0 } END { print m+0 }')"
  fi
  valid_epoch "\${wlh:-}" || wlh=0
  printf '%s' "$wlh"
}

# One "WG_PEER<TAB>publicKey<TAB>latestHandshake<TAB>rx<TAB>tx" line per peer, so
# PolySIEM can tell WHICH linked edge is handshaking rather than only that some
# peer is. Joined from two read-only queries: "wg show <if> dump" is deliberately
# NOT used, because its first line carries the interface's PRIVATE key.
wg_peer_lines() {
  command -v wg >/dev/null 2>&1 || return 0
  ip link show dev "$1" >/dev/null 2>&1 || return 0
  {
    wg show "$1" latest-handshakes 2>/dev/null || true
    printf '@\\n'
    wg show "$1" transfer 2>/dev/null || true
  } | awk -F '\\t' '
      BEGIN { phase = 1 }
      $1 == "@" { phase = 0; next }
      phase { if ($2 ~ /^[0-9]+$/) hs[$1] = $2; next }
      $1 ~ /^[A-Za-z0-9+\\/]+=$/ {
        printf "WG_PEER\\t%s\\t%s\\t%s\\t%s\\n", $1, ($1 in hs ? hs[$1] : "0"), ($2 ~ /^[0-9]+$/ ? $2 : "0"), ($3 ~ /^[0-9]+$/ ? $3 : "0")
      }'
}

handshake_age() {
  hs="$(wg_latest_handshake "$IFACE")"
  [ "$hs" -gt 0 ] || return 0
  now="$(date +%s 2>/dev/null || printf 0)"
  valid_epoch "$now" || return 0
  [ "$now" -gt "$hs" ] || return 0
  age=$((now - hs))
  # Clamped to the heartbeat schema's ceiling (one year) so a box that has been
  # offline for an absurdly long time still posts a heartbeat the API accepts.
  [ "$age" -le 31536000 ] || age=31536000
  printf '%s' "$age"
}

# -------------------------------------------------------------------- poll
# Fetches the desired config, re-validates every field, rebuilds the canonical
# ruleset locally and refuses to apply anything whose sha256 does not match the
# server-published configHash.
poll_config() {
  [ -n "$CONNECTOR_ID" ] || { log 'no connector id yet'; exit 3; }
  applied="$(kv_value "$STATE_FILE" HASH)"
  if valid_hash "$applied"; then applied_json="$(printf '"%s"' "$applied")"; else applied_json=null; fi
  hs_json=null
  hs="$(handshake_age)"
  [ -z "$hs" ] || hs_json="$hs"

  body="$(mktemp)"; chmod 0600 "$body"
  resp="$(mktemp)"; chmod 0600 "$resp"
  flat="$(mktemp)"; chmod 0600 "$flat"
  objects="$(mktemp)"; chmod 0600 "$objects"
  printf '{"connectorId":"%s","token":"%s","agentVersion":"%s","handshakeAgeSeconds":%s,"appliedConfigHash":%s}' \\
    "$CONNECTOR_ID" "$TOKEN" "$AGENT_VERSION" "$hs_json" "$applied_json" > "$body"
  if ! http_post /api/network/connectors/config "$body" "$resp"; then
    rm -f "$body" "$resp" "$flat" "$objects"
    log 'config poll failed'
    exit 5
  fi
  rm -f "$body"
  flatten_json "$resp" "$flat"

  CONFIG_HASH="$(json_str "$flat" configHash)"
  if ! valid_hash "$CONFIG_HASH"; then rm -f "$resp" "$flat" "$objects"; log 'config response had no usable configHash'; exit 5; fi
  if ! parse_config_head "$flat"; then rm -f "$resp" "$flat" "$objects"; exit 5; fi
  rm -f "$flat"
  write_tunnel_file 1

  raw_t="$(mktemp)"; chmod 0600 "$raw_t"; : > "$raw_t"
  raw_r="$(mktemp)"; chmod 0600 "$raw_r"; : > "$raw_r"
  refusal=""
  # Each JSON object lands on its own line, so a tunnel and a route can be told
  # apart by a key only one of them has and parsed in isolation.
  split_objects "$resp" | grep '"edgeKey"' > "$objects" || true
  parse_config_tunnels
  split_objects "$resp" | grep '"listenPort"' > "$objects" || true
  [ -n "$refusal" ] || parse_config_routes
  rm -f "$objects" "$resp"
  if [ -n "$refusal" ]; then
    rm -f "$raw_t" "$raw_r"
    log "$refusal"
    exit 5
  fi

  # Canonical form (must match canonicalConnectorRuleset byte for byte): header,
  # IFACE, then C-locale sorted and de-duplicated TUNNEL lines and ROUTE lines.
  RULESET_TMP="$(mktemp)"; chmod 0600 "$RULESET_TMP"
  {
    printf 'CXRULESET\\t%s\\n' "$RULESET_VERSION"
    printf 'IFACE\\t%s\\n' "$IFACE"
    LC_ALL=C sort -u "$raw_t"
    LC_ALL=C sort -u "$raw_r"
  } > "$RULESET_TMP"
  rm -f "$raw_t" "$raw_r"
  local_hash="$(sha256sum "$RULESET_TMP" | awk '{print $1}')"
  if [ "$local_hash" != "$CONFIG_HASH" ]; then
    rm -f "$RULESET_TMP"
    log 'published configHash does not match the parsed ruleset; not applying'
    exit 5
  fi
}

# One "tunnels" entry per linked edge. The loop reads from a file (not a pipe) so
# the counter and the refusal survive it.
parse_config_tunnels() {
  t_count=0
  while IFS= read -r frag; do
    [ -n "$frag" ] || continue
    tu_key="$(frag_str "$frag" edgeKey)"
    tu_addr="$(frag_str "$frag" address)"
    tu_end="$(frag_str "$frag" endpoint)"
    tu_pub="$(frag_str "$frag" publicKey)"
    tu_allow="$(frag_csv "$frag" allowedIps)"
    tu_keep="$(frag_num "$frag" persistentKeepalive)"
    valid_uint "$tu_keep" && [ "$tu_keep" -le 65535 ] || tu_keep=25
    if ! valid_edge_key "$tu_key" || ! valid_cidr "$tu_addr" || ! valid_endpoint "$tu_end" || \\
       ! valid_wgkey "$tu_pub" || ! valid_allowed_list "$tu_allow"; then
      refusal='refusing a malformed tunnel from the control plane'
      return 0
    fi
    t_count=$((t_count + 1))
    if [ "$t_count" -gt "$MAX_TUNNELS" ]; then
      refusal='refusing a ruleset with too many tunnels'
      return 0
    fi
    printf 'TUNNEL\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\n' "$tu_key" "$tu_addr" "$tu_end" "$tu_pub" "$tu_allow" "$tu_keep" >> "$raw_t"
  done < "$objects"
}

# One "routes" entry per published last-hop route. localAddress says WHICH edge
# published it, and becomes the -d scope of that route's DNAT rule.
parse_config_routes() {
  count=0
  while IFS= read -r frag; do
    [ -n "$frag" ] || continue
    r_local="$(frag_str "$frag" localAddress)"
    r_proto="$(frag_str "$frag" protocol)"
    r_lport="$(frag_num "$frag" listenPort)"
    r_target="$(frag_str "$frag" targetAddress)"
    r_tport="$(frag_num "$frag" targetPort)"
    if ! valid_ip "$r_local" || ! valid_proto "$r_proto" || ! valid_port "$r_lport" || \\
       ! valid_ip "$r_target" || ! valid_port "$r_tport"; then
      refusal='refusing a malformed route from the control plane'
      return 0
    fi
    count=$((count + 1))
    if [ "$count" -gt "$MAX_ROUTES" ]; then
      refusal='refusing a ruleset with too many routes'
      return 0
    fi
    printf 'ROUTE\\t%s\\t%s\\t%s\\t%s\\t%s\\n' "$r_local" "$r_proto" "$r_lport" "$r_target" "$r_tport" >> "$raw_r"
  done < "$objects"
}

# ------------------------------------------------------------------- apply
managed_iptables_hash() {
  r="$1"
  {
    iptables -t nat -S "$DNAT"
    iptables -t nat -S "$SNAT"
    iptables -S "$FWD"
    iptables -t nat -S "$GEN_D$r"
    iptables -t nat -S "$GEN_S$r"
    iptables -S "$GEN_F$r"
  } 2>/dev/null | sha256sum | awk '{print $1}'
}

dispatchers_linked() {
  r="$1"
  [ "$r" -gt 0 ] || return 1
  iptables -t nat -C "$DNAT" -j "$GEN_D$r" 2>/dev/null || return 1
  iptables -t nat -C "$SNAT" -j "$GEN_S$r" 2>/dev/null || return 1
  iptables -C "$FWD" -j "$GEN_F$r" 2>/dev/null || return 1
  return 0
}

# apply_ruleset <canonical ruleset file> <wanted hash> <revision|->
#
# "-" means "choose the next free generation number yourself" (the poll transport,
# which has no authoritative revision counter). A number means the control plane
# dictated the revision over SSH, and monotonicity/drift are enforced against the
# stored state exactly the way the edge agent does it: exit 5 for a stale or
# conflicting revision, exit 6 for drift that only a newer revision may repair.
apply_ruleset() {
  ruleset="$1"; wanted_hash="$2"; forced_revision="$3"
  exec 9>"$LOCK_FILE"
  flock -n 9 || { log 'another connector apply is already in progress'; exit 4; }

  old_revision="$(kv_value "$STATE_FILE" REVISION)"
  valid_uint "$old_revision" || old_revision=0
  old_d="$GEN_D$old_revision"; old_s="$GEN_S$old_revision"; old_f="$GEN_F$old_revision"
  revision=$old_revision
  new_d=""; new_s=""; new_f=""

  generation="$(mktemp)"; swap="$(mktemp)"; rollback="$(mktemp)"; state="$(mktemp)"
  committed=0; swap_started=0
  cleanup() {
    rc=$?
    if [ "$committed" -ne 1 ] && [ "$swap_started" -eq 1 ]; then
      iptables-restore --noflush < "$rollback" >/dev/null 2>&1 || true
    fi
    rm -f "$generation" "$swap" "$rollback" "$state" "$ruleset"
    exit "$rc"
  }
  trap cleanup EXIT HUP INT TERM

  count="$(grep -c '^ROUTE' "$ruleset" || true)"
  valid_uint "$count" || count=0

  if [ "$forced_revision" = - ]; then
    # Pick a free generation number. Normally that is old+1, but a hard kill in the
    # middle of an earlier swap can leave chains behind under that exact name. An
    # unreferenced leftover is reclaimed and a still-referenced one is skipped, so
    # the agent heals itself instead of wedging forever on a name collision. Only
    # PolySIEM-owned names are ever touched.
    attempts=0
    while : ; do
      revision=$((revision + 1))
      [ "$revision" -le 999999999 ] || revision=1
      attempts=$((attempts + 1))
      [ "$attempts" -le 64 ] || { log 'could not find a free generation chain name'; exit 6; }
      new_d="$GEN_D$revision"; new_s="$GEN_S$revision"; new_f="$GEN_F$revision"
      present=0
      iptables -t nat -S "$new_d" >/dev/null 2>&1 && present=1
      iptables -t nat -S "$new_s" >/dev/null 2>&1 && present=1
      iptables -S "$new_f" >/dev/null 2>&1 && present=1
      [ "$present" -eq 1 ] || break
      linked=0
      iptables -t nat -C "$DNAT" -j "$new_d" >/dev/null 2>&1 && linked=1
      iptables -t nat -C "$SNAT" -j "$new_s" >/dev/null 2>&1 && linked=1
      iptables -C "$FWD" -j "$new_f" >/dev/null 2>&1 && linked=1
      [ "$linked" -eq 0 ] || continue
      iptables -w -t nat -F "$new_d" 2>/dev/null && iptables -w -t nat -X "$new_d" 2>/dev/null || true
      iptables -w -t nat -F "$new_s" 2>/dev/null && iptables -w -t nat -X "$new_s" 2>/dev/null || true
      iptables -w -F "$new_f" 2>/dev/null && iptables -w -X "$new_f" 2>/dev/null || true
      break
    done
  else
    revision="$forced_revision"
    new_d="$GEN_D$revision"; new_s="$GEN_S$revision"; new_f="$GEN_F$revision"
    old_hash="$(kv_value "$STATE_FILE" HASH)"
    valid_hash "$old_hash" || old_hash=-
    if [ "$revision" -lt "$old_revision" ] || { [ "$revision" -eq "$old_revision" ] && [ "$wanted_hash" != "$old_hash" ]; }; then
      log 'stale or conflicting ruleset revision'
      exit 5
    fi
    links_present=0
    dispatchers_linked "$revision" && links_present=1
    stored_ipt="$(kv_value "$STATE_FILE" IPTABLES_HASH)"
    # Already exactly this revision, this hash, and nothing has drifted: report
    # success without touching a single rule.
    if [ "$revision" -eq "$old_revision" ] && [ "$wanted_hash" = "$old_hash" ] && [ "$links_present" -eq 1 ] && \\
       valid_hash "$stored_ipt" && [ "$(managed_iptables_hash "$revision")" = "$stored_ipt" ]; then
      printf 'APPLIED\\t%s\\t%s\\t%s\\n' "$count" "$revision" "$wanted_hash"
      committed=1
      exit 0
    fi
    if [ "$revision" -eq "$old_revision" ] && [ "$links_present" -eq 1 ]; then
      log 'managed rules drifted; submit a newer revision to repair them'
      exit 6
    fi
    # An interrupted earlier attempt may have left unreferenced chains under this
    # exact revision. Reclaim only those exact PolySIEM names.
    if iptables -t nat -S "$new_d" >/dev/null 2>&1; then
      iptables -t nat -C "$DNAT" -j "$new_d" >/dev/null 2>&1 && exit 6
      iptables -w -t nat -F "$new_d" && iptables -w -t nat -X "$new_d"
    fi
    if iptables -t nat -S "$new_s" >/dev/null 2>&1; then
      iptables -t nat -C "$SNAT" -j "$new_s" >/dev/null 2>&1 && exit 6
      iptables -w -t nat -F "$new_s" && iptables -w -t nat -X "$new_s"
    fi
    if iptables -S "$new_f" >/dev/null 2>&1; then
      iptables -C "$FWD" -j "$new_f" >/dev/null 2>&1 && exit 6
      iptables -w -F "$new_f" && iptables -w -X "$new_f"
    fi
  fi

  # Every last-hop DNAT is scoped by DESTINATION as well as by port: two edges may
  # publish the same public port to this one connector, and without "-d
  # <localAddress>" the second one would be shadowed by the first. The address is
  # this connector's own tunnel address on the edge that published the route, and
  # ensure_tunnels has already put it on the interface.
  #
  # The masquerade and forward rules key on the TARGET (after DNAT the destination
  # is the internal service, not the tunnel address), so two edges publishing to
  # the same internal service produce one shared rule: "sort -u" collapses them
  # rather than installing a duplicate.
  {
    printf '*nat\\n:%s - [0:0]\\n:%s - [0:0]\\n' "$new_d" "$new_s"
    while IFS="$TAB" read -r kind laddr proto lport target tport; do
      [ "$kind" = ROUTE ] || continue
      printf -- '-A %s -i %s -d %s -p %s --dport %s -j DNAT --to-destination %s:%s\\n' "$new_d" "$IFACE" "$laddr" "$proto" "$lport" "$target" "$tport"
    done < "$ruleset"
    while IFS="$TAB" read -r kind laddr proto lport target tport; do
      [ "$kind" = ROUTE ] || continue
      printf -- '-A %s -p %s -d %s --dport %s -m conntrack --ctstate DNAT -j MASQUERADE\\n' "$new_s" "$proto" "$target" "$tport"
    done < "$ruleset" | LC_ALL=C sort -u
    printf 'COMMIT\\n*filter\\n:%s - [0:0]\\n' "$new_f"
    while IFS="$TAB" read -r kind laddr proto lport target tport; do
      [ "$kind" = ROUTE ] || continue
      printf -- '-A %s -i %s -p %s -d %s --dport %s -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT\\n' "$new_f" "$IFACE" "$proto" "$target" "$tport"
      printf -- '-A %s -o %s -p %s -s %s --sport %s -m conntrack --ctstate ESTABLISHED -j ACCEPT\\n' "$new_f" "$IFACE" "$proto" "$target" "$tport"
    done < "$ruleset" | LC_ALL=C sort -u
    printf 'COMMIT\\n'
  } > "$generation"

  iptables-restore --test --noflush < "$generation"
  iptables-restore --noflush < "$generation"

  # The three stable dispatchers are the only global hooks; non-matching traffic
  # returns immediately to the operator-owned ruleset.
  iptables -w -t nat -N "$DNAT" 2>/dev/null || iptables -w -t nat -S "$DNAT" >/dev/null
  iptables -w -t nat -N "$SNAT" 2>/dev/null || iptables -w -t nat -S "$SNAT" >/dev/null
  iptables -w -N "$FWD" 2>/dev/null || iptables -w -S "$FWD" >/dev/null
  iptables -w -t nat -C PREROUTING -j "$DNAT" 2>/dev/null || iptables -w -t nat -I PREROUTING 1 -j "$DNAT"
  iptables -w -t nat -C POSTROUTING -j "$SNAT" 2>/dev/null || iptables -w -t nat -I POSTROUTING 1 -j "$SNAT"
  iptables -w -C FORWARD -j "$FWD" 2>/dev/null || iptables -w -I FORWARD 1 -j "$FWD"

  {
    printf '*nat\\n:%s - [0:0]\\n:%s - [0:0]\\n-A %s -j %s\\n-A %s -j %s\\nCOMMIT\\n' "$DNAT" "$SNAT" "$DNAT" "$new_d" "$SNAT" "$new_s"
    printf '*filter\\n:%s - [0:0]\\n-A %s -j %s\\nCOMMIT\\n' "$FWD" "$FWD" "$new_f"
  } > "$swap"
  {
    printf '*nat\\n:%s - [0:0]\\n:%s - [0:0]\\n' "$DNAT" "$SNAT"
    if [ "$old_revision" -gt 0 ]; then printf -- '-A %s -j %s\\n-A %s -j %s\\n' "$DNAT" "$old_d" "$SNAT" "$old_s"; fi
    printf 'COMMIT\\n*filter\\n:%s - [0:0]\\n' "$FWD"
    if [ "$old_revision" -gt 0 ]; then printf -- '-A %s -j %s\\n' "$FWD" "$old_f"; fi
    printf 'COMMIT\\n'
  } > "$rollback"
  iptables-restore --test --noflush < "$swap"

  [ "$count" -eq 0 ] || sysctl -w net.ipv4.ip_forward=1 >/dev/null
  swap_started=1
  iptables-restore --noflush < "$swap"

  iptables_hash="$(managed_iptables_hash "$revision")"
  valid_hash "$iptables_hash" || { log 'could not verify the applied generation'; exit 6; }
  printf 'REVISION\\t%s\\nHASH\\t%s\\nCOUNT\\t%s\\nIPTABLES_HASH\\t%s\\nIFACE\\t%s\\nAGENT_VERSION\\t%s\\n' \\
    "$revision" "$wanted_hash" "$count" "$iptables_hash" "$IFACE" "$AGENT_VERSION" > "$state"
  chmod 0600 "$state"
  mv "$state" "$STATE_FILE"
  # Remember the exact bytes that were applied. This is the agent's record of
  # every edge it is linked to: the boot path replays these TUNNEL lines to bring
  # all peers and addresses back without waiting for a poll or an SSH push.
  install -m 0600 "$ruleset" "$RULESET_FILE.new"
  mv "$RULESET_FILE.new" "$RULESET_FILE"
  committed=1

  # Retire every PolySIEM generation chain except the one just committed. This
  # runs only after the new dispatchers and the new state file are durable, and
  # the dispatchers now reference nothing else, so each of these is unreferenced.
  # The name pattern cannot match the dispatchers themselves (PS_CX_DNAT / _SNAT /
  # _FORWARD have no numeric generation suffix).
  for stale in $(iptables -t nat -S 2>/dev/null | sed -n 's/^-N \\(PS_CX_[DS]_[0-9][0-9]*\\)$/\\1/p'); do
    [ "$stale" != "$new_d" ] && [ "$stale" != "$new_s" ] || continue
    iptables -w -t nat -F "$stale" 2>/dev/null && iptables -w -t nat -X "$stale" 2>/dev/null || true
  done
  for stale in $(iptables -S 2>/dev/null | sed -n 's/^-N \\(PS_CX_F_[0-9][0-9]*\\)$/\\1/p'); do
    [ "$stale" != "$new_f" ] || continue
    iptables -w -F "$stale" 2>/dev/null && iptables -w -X "$stale" 2>/dev/null || true
  done
  printf 'APPLIED\\t%s\\t%s\\t%s\\n' "$count" "$revision" "$wanted_hash"
}

maybe_apply() {
  stored_hash="$(kv_value "$STATE_FILE" HASH)"
  stored_revision="$(kv_value "$STATE_FILE" REVISION)"
  valid_uint "$stored_revision" || stored_revision=0
  need=0
  [ "$CONFIG_HASH" = "$stored_hash" ] || need=1
  if [ "$need" -eq 0 ] && ! dispatchers_linked "$stored_revision"; then need=1; fi
  if [ "$need" -eq 0 ]; then
    stored_ipt="$(kv_value "$STATE_FILE" IPTABLES_HASH)"
    [ "$(managed_iptables_hash "$stored_revision")" = "$stored_ipt" ] || need=1
  fi
  # The remembered ruleset must also still be the one the state claims, or the
  # boot path would replay the wrong set of peers.
  if [ "$need" -eq 0 ]; then
    [ -s "$RULESET_FILE" ] && [ "$(sha256sum "$RULESET_FILE" | awk '{print $1}')" = "$stored_hash" ] || need=1
  fi
  if [ "$need" -eq 0 ]; then
    rm -f "$RULESET_TMP"
    return 0
  fi
  apply_ruleset "$RULESET_TMP" "$CONFIG_HASH" -
}

# --------------------------------------------------------------- subcommands
cmd_once() {
  check_deps
  setup_tmp
  load_config
  load_token
  load_tunnel_file
  ensure_enrolled
  resume_tunnels
  poll_config
  ensure_tunnels "$RULESET_TMP"
  maybe_apply
}

cmd_run() {
  self="$0"
  case "$self" in /*) ;; *) self=${CONNECTOR_AGENT_PATH};; esac
  check_deps
  setup_tmp
  while : ; do
    rc=0
    "$self" once || rc=$?
    [ "$rc" -eq 0 ] || log "poll cycle failed (exit $rc); retrying"
    interval="$(kv_value "$TUNNEL_FILE" POLL_INTERVAL)"
    valid_uint "$interval" || interval=$DEFAULT_POLL
    [ "$interval" -ge "$MIN_POLL" ] || interval=$MIN_POLL
    [ "$interval" -le "$MAX_POLL" ] || interval=$MAX_POLL
    sleep "$interval"
  done
}

# ------------------------------------------------- SSH forced-command: APPLY
# Wire protocol v2 (frozen, tab-delimited, read from stdin after the APPLY line):
#
#   META<TAB><revision><TAB><rulesetHash>
#   IFACE<TAB><interfaceName>
#   TUNNEL<TAB><edgeKey><TAB><addressCidr><TAB><edgeEndpoint><TAB><edgePublicKey><TAB><allowedIpsCsv><TAB><keepalive>
#   ROUTE<TAB><localAddress><TAB><proto><TAB><listenPort><TAB><targetAddress><TAB><targetPort>
#   END
#
# ONE interface, one TUNNEL line per edge this connector is linked to, and every
# ROUTE tagged with the tunnel address of the edge that published it. TUNNEL and
# ROUTE lines may arrive in any order: the canonical rebuild sorts each block.
#
# There is no private-key field: this agent already owns its WireGuard identity,
# re-uses it with every edge, and generates one here if it has none yet. Only the
# edge's PUBLIC key ever arrives on this wire.
cmd_apply() {
  check_apply_deps
  setup_tmp
  load_config_soft
  load_tunnel_file

  IFS="$TAB" read -r m_kind m_rev m_hash m_extra || { log 'truncated APPLY: META line missing'; exit 2; }
  [ "$m_kind" = META ] && [ -z "\${m_extra:-}" ] || { log 'malformed META line'; exit 2; }
  valid_revision "$m_rev" || { log 'malformed revision on the META line'; exit 2; }
  valid_hash "$m_hash" || { log 'malformed ruleset hash on the META line'; exit 2; }

  IFS="$TAB" read -r i_kind i_if i_extra || { log 'truncated APPLY: IFACE line missing'; exit 2; }
  [ "$i_kind" = IFACE ] && [ -z "\${i_extra:-}" ] || { log 'malformed IFACE line'; exit 2; }
  valid_if "$i_if" || { log 'malformed tunnel interface name'; exit 2; }
  IFACE="$i_if"

  raw_t="$(mktemp)"; chmod 0600 "$raw_t"; : > "$raw_t"
  raw_r="$(mktemp)"; chmod 0600 "$raw_r"; : > "$raw_r"
  t_count=0; r_count=0; saw_end=0; refusal=""
  parse_apply_body
  if [ -n "$refusal" ]; then rm -f "$raw_t" "$raw_r"; log "$refusal"; exit 2; fi
  if IFS= read -r trailing; then
    [ -z "$trailing" ] || { rm -f "$raw_t" "$raw_r"; log 'unexpected data after END'; exit 2; }
  fi

  # Recompute the canonical ruleset locally and fail closed on any mismatch: the
  # hash on the wire is only ever a claim about what these lines add up to.
  RULESET_TMP="$(mktemp)"; chmod 0600 "$RULESET_TMP"
  {
    printf 'CXRULESET\\t%s\\n' "$RULESET_VERSION"
    printf 'IFACE\\t%s\\n' "$IFACE"
    LC_ALL=C sort -u "$raw_t"
    LC_ALL=C sort -u "$raw_r"
  } > "$RULESET_TMP"
  rm -f "$raw_t" "$raw_r"
  local_hash="$(sha256sum "$RULESET_TMP" | awk '{print $1}')"
  if [ "$local_hash" != "$m_hash" ]; then
    rm -f "$RULESET_TMP"
    log 'ruleset hash does not match the lines on the wire; not applying'
    exit 2
  fi

  # Our own key, generated here if this box has never had one, and re-used with
  # every peer. Peers and addresses are reconciled against exactly these tunnels.
  ensure_keypair
  ensure_tunnels "$RULESET_TMP"

  prev_enrolled="$(kv_value "$TUNNEL_FILE" ENROLLED)"
  [ "$prev_enrolled" = 1 ] || prev_enrolled=0
  write_tunnel_file "$prev_enrolled"

  apply_ruleset "$RULESET_TMP" "$m_hash" "$m_rev"
}

# The TUNNEL/ROUTE/END block of an APPLY. Reads stdin until END, validating every
# field of every line and refusing the whole payload on the first bad one.
parse_apply_body() {
  while IFS="$TAB" read -r a1 a2 a3 a4 a5 a6 a7 a8; do
    case "$a1" in
      END)
        [ -z "\${a2:-}\${a3:-}\${a4:-}\${a5:-}\${a6:-}\${a7:-}\${a8:-}" ] || refusal='unexpected fields on the END line'
        saw_end=1
        return 0
        ;;
      TUNNEL)
        [ -z "\${a8:-}" ] || { refusal='malformed TUNNEL line'; return 0; }
        valid_uint "$a7" && [ "$a7" -le 65535 ] || { refusal='malformed persistent keepalive'; return 0; }
        if ! valid_edge_key "$a2" || ! valid_cidr "$a3" || ! valid_endpoint "$a4" || \\
           ! valid_wgkey "$a5" || ! valid_allowed_list "$a6"; then
          refusal='refusing a malformed tunnel from the control plane'
          return 0
        fi
        t_count=$((t_count + 1))
        [ "$t_count" -le "$MAX_TUNNELS" ] || { refusal='refusing a ruleset with too many tunnels'; return 0; }
        printf 'TUNNEL\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\n' "$a2" "$a3" "$a4" "$a5" "$a6" "$a7" >> "$raw_t"
        ;;
      ROUTE)
        [ -z "\${a7:-}\${a8:-}" ] || { refusal='malformed ROUTE line'; return 0; }
        if ! valid_ip "$a2" || ! valid_proto "$a3" || ! valid_port "$a4" || ! valid_ip "$a5" || ! valid_port "$a6"; then
          refusal='refusing a malformed route from the control plane'
          return 0
        fi
        r_count=$((r_count + 1))
        [ "$r_count" -le "$MAX_ROUTES" ] || { refusal='refusing a ruleset with too many routes'; return 0; }
        printf 'ROUTE\\t%s\\t%s\\t%s\\t%s\\t%s\\n' "$a2" "$a3" "$a4" "$a5" "$a6" >> "$raw_r"
        ;;
      *)
        refusal='unexpected line in the APPLY payload'
        return 0
        ;;
    esac
  done
  [ "$saw_end" -eq 1 ] || refusal='truncated ruleset: END missing'
}

# ------------------------------------------------ SSH forced-command: STATUS
# Prints only non-secret facts: never the token, never the private key. Every wg
# and ip call is guarded so a box that has never been provisioned still returns a
# complete, parsable STATUS. Read-only — it creates and changes nothing.
cmd_status() {
  load_config_soft
  load_tunnel_file
  printf '${CONNECTOR_STATUS_BANNER}\\n'
  printf 'HOSTNAME\\t%s\\n' "$(sanitize "$(uname -n 2>/dev/null || printf -)")"
  printf 'KERNEL\\t%s\\n' "$(sanitize "$(uname -srmo 2>/dev/null || printf -)")"
  printf 'AGENT_VERSION\\t%s\\n' "$AGENT_VERSION"
  printf 'CONNECTOR_ID\\t%s\\n' "\${CONNECTOR_ID:--}"
  enrolled_flag="$(kv_value "$TUNNEL_FILE" ENROLLED)"
  [ "$enrolled_flag" = 1 ] || enrolled_flag=0
  printf 'ENROLLED\\t%s\\n' "$enrolled_flag"
  edge_endpoint="$(ruleset_field TUNNEL 4)"
  valid_endpoint "\${edge_endpoint:-}" || edge_endpoint=-
  printf 'EDGE_ENDPOINT\\t%s\\n' "$edge_endpoint"
  printf 'WG_IF\\t%s\\n' "$IFACE"
  printf 'WG_PUBKEY\\t%s\\n' "$(connector_public_key "$IFACE")"
  printf 'WG_STATE\\t%s\\n' "$(wg_link_state "$IFACE")"
  printf 'WG_ADDRESS\\t%s\\n' "$(wg_link_address "$IFACE")"
  printf 'WG_LATEST_HANDSHAKE\\t%s\\n' "$(wg_latest_handshake "$IFACE")"
  printf 'WG_PEERS\\t%s\\n' "$(wg_peer_count "$IFACE")"
  printf 'WG_TUNNELS\\t%s\\n' "$(ruleset_tunnel_count)"
  # One line per peer, so PolySIEM can attribute a handshake to a specific linked
  # edge instead of guessing from the aggregate. Additive: every aggregate key
  # above is still reported, and a parser that ignores unknown keys is unaffected.
  wg_peer_lines "$IFACE"
  printf 'IP_FORWARD\\t%s\\n' "$(sysctl -n net.ipv4.ip_forward 2>/dev/null || printf 0)"
  revision="$(kv_value "$STATE_FILE" REVISION)"
  valid_uint "$revision" || revision=0
  printf 'APPLIED_REVISION\\t%s\\n' "$revision"
  applied="$(kv_value "$STATE_FILE" HASH)"
  valid_hash "$applied" || applied=-
  printf 'APPLIED_HASH\\t%s\\n' "$applied"
  drift=0
  if [ "$revision" -gt 0 ]; then
    dispatchers_linked "$revision" || drift=1
    [ "$drift" -eq 1 ] || [ "$(managed_iptables_hash "$revision")" = "$(kv_value "$STATE_FILE" IPTABLES_HASH)" ] || drift=1
  fi
  printf 'RULESET_DRIFT\\t%s\\n' "$drift"
  route_count="$(kv_value "$STATE_FILE" COUNT)"
  valid_uint "$route_count" || route_count=0
  printf 'ROUTE_COUNT\\t%s\\n' "$route_count"
  ip -o -4 addr show 2>/dev/null | sed 's/^/ADDRESS\\t/' | awk '{ print substr($0, 1, 1024) }' || true
}

# The agent is reached three ways:
#   * systemd:            <agent> run
#   * an operator shell:  <agent> once|status|version
#   * an SSH forced command: sshd runs it with NO arguments and the request
#     arrives on stdin, exactly like the PolySIEM edge agent. The first line
#     names the action; APPLY's payload follows on the same stream.
if [ "$#" -eq 0 ] && [ ! -t 0 ]; then
  IFS= read -r stdin_action || stdin_action=""
  stdin_action="\${stdin_action%$CR}"
  set -- "\${stdin_action:-run}"
fi
action="\${1:-run}"
case "$action" in
  run) cmd_run ;;
  once) cmd_once ;;
  status) cmd_status ;;
  STATUS) cmd_status ;;
  APPLY) cmd_apply ;;
  version) printf '%s\\n' "$AGENT_VERSION" ;;
  *) printf 'usage: polysiem-connector-agent [run|once|status|version]\\n' >&2; exit 2 ;;
esac
`;
