param(
    [string]$InstallDir = $env:POLYSIEM_INSTALL_DIR,
    [string]$Repository = $env:POLYSIEM_GITHUB_REPOSITORY
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

if (-not $InstallDir) {
    $base = if ($env:LOCALAPPDATA) { $env:LOCALAPPDATA } else { $env:ProgramData }
    $InstallDir = Join-Path $base "PolySIEM"
}
if (-not $Repository) { $Repository = "Realynx/PolySIEM" }
if ($Repository -notmatch '^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$') {
    throw "Repository must use the owner/repository format."
}

$ReleaseBase = "https://github.com/$Repository/releases/latest/download"
$Image = ""
$EnvFile = Join-Path $InstallDir ".env"
$ComposeFile = Join-Path $InstallDir "docker-compose.yml"
$UpdaterFile = Join-Path $InstallDir "update.ps1"

function Write-PolySIEMLog([string]$Message) {
    Write-Host "[polysiem] $Message" -ForegroundColor Cyan
}

function Invoke-Docker([string[]]$Arguments) {
    & docker @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "docker $($Arguments -join ' ') failed with exit code $LASTEXITCODE"
    }
}

function New-HexSecret([int]$Bytes) {
    $buffer = New-Object byte[] $Bytes
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try { $rng.GetBytes($buffer) } finally { $rng.Dispose() }
    return ([BitConverter]::ToString($buffer)).Replace("-", "").ToLowerInvariant()
}

function Get-HostAddress {
    try {
        $socket = New-Object System.Net.Sockets.UdpClient
        try {
            $socket.Connect("8.8.8.8", 65530)
            $endpoint = [System.Net.IPEndPoint]$socket.Client.LocalEndPoint
            if ($endpoint.Address) { return $endpoint.Address.IPAddressToString }
        } finally {
            $socket.Dispose()
        }
    } catch { }
    return "localhost"
}

function Test-PolySIEMHealth {
    # The app serves HTTPS with a self-signed certificate by default; fall back
    # to plain HTTP for POLYSIEM_TLS=off setups and older images.
    foreach ($uri in @("https://localhost:3000/api/health", "http://localhost:3000/api/health")) {
        try {
            if ($PSVersionTable.PSEdition -eq "Core") {
                $response = Invoke-WebRequest -UseBasicParsing -SkipCertificateCheck -Uri $uri -TimeoutSec 5
            } else {
                $previous = [System.Net.ServicePointManager]::ServerCertificateValidationCallback
                [System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }
                try {
                    $response = Invoke-WebRequest -UseBasicParsing -Uri $uri -TimeoutSec 5
                } finally {
                    [System.Net.ServicePointManager]::ServerCertificateValidationCallback = $previous
                }
            }
            if ($response.StatusCode -eq 200) { return $true }
        } catch { }
    }
    return $false
}

function Add-EnvSetting([string]$Name, [string]$Value) {
    $content = Get-Content -LiteralPath $EnvFile -Raw
    if ($content -notmatch "(?m)^$([Regex]::Escape($Name))=") {
        Add-Content -LiteralPath $EnvFile -Encoding Ascii -Value "$Name=$Value"
    }
}

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    throw "Docker Desktop is required. Install and start Docker Desktop, then run this command again."
}
Invoke-Docker @("info")
Invoke-Docker @("compose", "version")

Write-PolySIEMLog "Reading the latest release metadata..."
$manifest = (Invoke-WebRequest -UseBasicParsing -Uri "$ReleaseBase/release-manifest.json").Content | ConvertFrom-Json
$Image = [string]$manifest.image
if ($Image -notmatch '^ghcr\.io/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+:[A-Za-z0-9_.-]+$') {
    throw "The GitHub release manifest contains an invalid container image."
}

New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
if (-not (Test-Path -LiteralPath $EnvFile)) {
    Write-PolySIEMLog "Generating configuration and encryption secrets..."
    $dbPassword = New-HexSecret 24
    $appSecret = New-HexSecret 32
    $hostAddress = Get-HostAddress
    $content = @"
# PolySIEM configuration generated by install.ps1. Back this file up.
DATABASE_URL=postgresql://polysiem:$dbPassword@db:5432/polysiem
APP_SECRET=$appSecret
APP_URL=https://${hostAddress}:3000
DB_PASSWORD=$dbPassword
POLYSIEM_IMAGE=$Image
POLYSIEM_GITHUB_REPOSITORY=$Repository
POLYSIEM_INSTALL_TYPE=windows-docker
"@
    Set-Content -LiteralPath $EnvFile -Encoding Ascii -Value $content
} else {
    Write-PolySIEMLog "Keeping existing $EnvFile (secrets preserved)."
    Add-EnvSetting "POLYSIEM_IMAGE" $Image
    Add-EnvSetting "POLYSIEM_GITHUB_REPOSITORY" $Repository
    Add-EnvSetting "POLYSIEM_INSTALL_TYPE" "windows-docker"
}

Write-PolySIEMLog "Downloading release deployment files..."
Invoke-WebRequest -UseBasicParsing -Uri "$ReleaseBase/docker-compose.yml" -OutFile $ComposeFile
Invoke-WebRequest -UseBasicParsing -Uri "$ReleaseBase/update.ps1" -OutFile $UpdaterFile

Push-Location $InstallDir
try {
    Write-PolySIEMLog "Pulling and starting PolySIEM..."
    Invoke-Docker @("compose", "pull")
    Invoke-Docker @("compose", "up", "-d")
} finally {
    Pop-Location
}

Write-PolySIEMLog "Waiting for PolySIEM to become healthy..."
$healthy = $false
for ($attempt = 0; $attempt -lt 45; $attempt++) {
    if (Test-PolySIEMHealth) { $healthy = $true; break }
    Start-Sleep -Seconds 2
}
if (-not $healthy) {
    throw "PolySIEM did not become healthy within 90 seconds. Run: cd '$InstallDir'; docker compose logs polysiem"
}

$updateCommand = "powershell -ExecutionPolicy Bypass -File `"$UpdaterFile`""
Write-Host ""
Write-Host "PolySIEM is running at https://localhost:3000" -ForegroundColor Green
Write-Host "(self-signed certificate - your browser warns once; replace it under Settings > Web certificate)"
Write-Host "Update command: $updateCommand"
Write-Host "Data directory: $InstallDir"
