import { z } from "zod";
import { generateSshKey } from "@/lib/services/ssh-keys";
import type { ActionDefinition } from "../registry";

const configSchema = z.object({
  name: z.string().min(1).max(128),
  comment: z.string().max(128).optional(),
});

/**
 * ssh.generate-key — generate a fresh ed25519 keypair. Only the PUBLIC key is
 * stored (SshKey row — the schema deliberately has no private-key column);
 * the private key is a SECRET output: redacted from persisted step output and
 * returned exactly once in the run response.
 */
export const sshGenerateKey: ActionDefinition = {
  meta: {
    kind: "ssh.generate-key",
    title: "Generate SSH key",
    description:
      "Generates an ed25519 keypair and documents the public key in SSH keys. The private key is returned once in the run result and never stored.",
    category: "ssh",
    inputs: [
      {
        key: "name",
        label: "Key name",
        type: "string",
        required: true,
        placeholder: "{{input.name}}",
        help: "Display name for the documented key (templateable).",
      },
      {
        key: "comment",
        label: "Comment",
        type: "string",
        required: false,
        help: "Key comment; defaults to <name>@polysiem.",
      },
    ],
    outputs: [
      { key: "sshKeyId", label: "SSH key id" },
      { key: "publicKey", label: "Public key line" },
      { key: "fingerprint", label: "Fingerprint" },
      { key: "privateKey", label: "Private key (PEM)", secret: true },
    ],
  },
  configSchema,
  async run({ config, ctx }) {
    const { name, comment } = configSchema.parse(config);
    const { key, privateKeyPem } = await generateSshKey(ctx.actor, {
      name,
      comment: comment?.trim() || undefined,
      purpose: "Generated by a PolySIEM workflow run",
    });
    return {
      sshKeyId: key.id,
      publicKey: key.publicKey,
      fingerprint: key.fingerprint,
      privateKey: privateKeyPem,
    };
  },
};
