import { z } from "zod";
import type { ActionDefinition } from "../registry";
import { executeParameterizedTrigger } from "./trigger-run";

export const WEBHOOK_TRIGGER_KIND = "trigger.webhook";

/**
 * trigger.webhook — starts the workflow from an inbound HTTP POST. Config is
 * { params: TriggerParam[], token: string }: params are validated against the
 * request body exactly like trigger.manual validates the run form, and the
 * unguessable token (generated by the service on save, "whk_" prefix) is the
 * only authentication of POST /api/workflows/hooks/[token].
 */
export const triggerWebhook: ActionDefinition = {
  meta: {
    kind: WEBHOOK_TRIGGER_KIND,
    title: "Webhook trigger",
    description:
      "Starts the workflow when a JSON object is POSTed to its hook URL. The secret token in the URL authenticates the caller; the body is validated against the declared parameters and exposed as {{input.<key>}}.",
    category: "trigger",
    // Config ({ params, token }) is edited with the dedicated trigger panel
    // (params editor + hook-URL display) in the builder, not a generic form.
    inputs: [],
    // Outputs are dynamic: one per declared param.
    outputs: [],
  },
  configSchema: z.object({
    params: z.array(z.unknown()).default([]),
    token: z.string().default(""),
  }),
  async run({ config, ctx }) {
    return executeParameterizedTrigger(
      config,
      ctx.input,
      "Invalid webhook payload",
    );
  },
};
